name: Eden
options:
  bundleIdPrefix: com.TheProxyCompany
configs:
  Debug: debug
  Release: release
packages:
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: 2.7.1
targets:
  Eden:
    type: application
    platform: macOS
    deploymentTarget: "14.6"
    sources:
      - path: Eden
    settings:
      base:
        INFOPLIST_FILE: Eden/Info.plist
        CODE_SIGN_ENTITLEMENTS: Eden/Eden.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_IDENTITY: Apple Development
        CODE_SIGN_STYLE: Automatic
        COMBINE_HIDPI_IMAGES: YES
        CURRENT_PROJECT_VERSION: 1
        DEVELOPMENT_TEAM: VLCRW7JPY7
        ENABLE_APP_SANDBOX: YES
        ENABLE_HARDENED_RUNTIME: YES
        ENABLE_PREVIEWS: YES
        ENABLE_USER_SELECTED_FILES: readonly
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_KEY_CFBundleDisplayName: Eden
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.utilities
        INFOPLIST_KEY_NSHumanReadableCopyright: ""
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        MACOSX_DEPLOYMENT_TARGET: 14.6
        MARKETING_VERSION: 0.0.1
        PRODUCT_BUNDLE_IDENTIFIER: com.TheProxyCompany.Eden
        PRODUCT_NAME: "$(TARGET_NAME)"
        PROVISIONING_PROFILE_SPECIFIER: ""
        REGISTER_APP_GROUPS: YES
        SUPPORTED_PLATFORMS: macosx
        SUPPORTS_MACCATALYST: NO
        SWIFT_EMIT_LOC_STRINGS: YES
        SWIFT_VERSION: 5.0
    dependencies:
      - package: Sparkle
  EdenTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: "14.6"
    sources:
      - path: EdenTests
    settings:
      base:
        BUNDLE_LOADER: "$(TEST_HOST)"
        CODE_SIGN_STYLE: Automatic
        CURRENT_PROJECT_VERSION: 1
        DEVELOPMENT_TEAM: VLCRW7JPY7
        GENERATE_INFOPLIST_FILE: YES
        MACOSX_DEPLOYMENT_TARGET: 14.6
        MARKETING_VERSION: 1.0
        PRODUCT_BUNDLE_IDENTIFIER: com.TheProxyCompany.EdenTests
        PRODUCT_NAME: "$(TARGET_NAME)"
        SWIFT_EMIT_LOC_STRINGS: NO
        SWIFT_VERSION: 5.0
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Eden.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Eden"
    dependencies:
      - target: Eden
schemes:
  Eden:
    build:
      targets:
        Eden: all
        EdenTests: test
    test:
      config: Debug
      gatherCoverageData: false
      targets:
        - name: EdenTests
